export const SELECT_CHAT_ACTION = 'view.SELECT_CHAT_ACTION'

export const SHOW_CHAT_CREATE_MODAL = 'view.SHOW_CHAT_CREATE_MODAL'
export const CLOSE_CHAT_CREATE_MODAL = 'view.CLOSE_CHAT_CREATE_MODAL'

export const SHOW_CONTACT_ADD_MODAL = 'view.SHOW_CONTACT_ADD_MODAL'
export const CLOSE_CONTACT_ADD_MODAL = 'view.CLOSE_CONTACT_ADD_MODAL'

export const SHOW_PROFILE_MODAL = 'view.SHOW_PROFILE_MODAL'
export const CLOSE_PROFILE_MODAL = 'view.CLOSE_PROFILE_MODAL'

export const entities = {
    CHAT_CREATE_MODAL: 'entity/CHAT_CREATE_MODAL',
    CONTACT_ADD_MODAL: 'entity/CONTACT_ADD_MODAL',
    PROFILE_MODAL: 'entity/PROFILE_MODAL'
}
