export const INITIAL_SESSION_ACTION = 'user.INITIAL_SESSION_ACTION'

export const FETCH_PROFILE_ACTION = 'user.FETCH_PROFILE_ACTION'
export const FETCH_PROFILE_REQUEST = 'user.FETCH_PROFILE_REQUEST'
export const FETCH_PROFILE_SUCCESS = 'user.FETCH_PROFILE_SUCCESS'

export const UPDATE_USER_ACTION = 'user.UPDATE_USER_ACTION'
export const UPDATE_USER_REQUEST = 'user.UPDATE_USER_REQUEST'
export const UPDATE_USER_FAILED = 'user.UPDATE_USER_FAILED'
